# The circleCI golang:1.9 docker image doesn't have other archs installed
docker-golang: &docker-golang
  working_directory: /go/src/github.com/palantir/duo-bot
  docker:
    - image: golang:1.9
      environment:
        CGO_ENABLED: 0

# Shared tasks
define-artifact-dir: &define-artifacts-dir
  run: echo "export ARTIFACT_STORE=/tmp/artifacts/${CIRCLE_PROJECT_REPONAME}-${TAG_NAME}-tests" >> $BASH_ENV

install-docker-client: &install-docker-client
  run:
    name: Install docker client
    command: |
      set -x
      VER="17.05.0-ce"
      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      mv /tmp/docker/* /usr/bin

build-docker-image: &build-docker-image
  run:
    name: Build docker image
    command: |
      set -x
      version=$(./godelw project-version)

      cp /etc/ssl/certs/ca-certificates.crt .
      docker build \
        -t palantirtechnologies/duo-bot \
        --build-arg VERSION=${version} \
        -f Dockerfile \
        .
      rm -f ca-certificates.crt

mkdir-artifacts-dir: &mkdir-artifacts-dir
  run: mkdir -p "${ARTIFACT_STORE}"

store-test-results: &store-test-results
  type: test-results-store
  path: /tmp/artifacts

store-artifacts: &store-artifacts
  type: artifacts-store
  path: /tmp/artifacts

version: 2
jobs:
  build:
    <<: *docker-golang

    steps:
      - checkout
      - *define-artifacts-dir
      - *mkdir-artifacts-dir

      - run: go version
      - run: ./godelw version

      - setup_remote_docker
      - *install-docker-client
      - run: ./godelw verify --apply=false --junit-output="${ARTIFACT_STORE}/tests.xml"
      - run: ./godelw dist
      - *build-docker-image

      - *store-test-results

  # Only generate a changelog for master builds, use generated changelog as git release tag message
  changelog:
    machine: true

    steps:
      - checkout
      - *define-artifacts-dir
      - *mkdir-artifacts-dir
      - run: git log `git describe --tags --abbrev=0`..HEAD --pretty="### %s%n%b%n" > /tmp/artifacts/changelog.md
      - *store-artifacts

  publish:
    <<: *docker-golang

    steps:
      - checkout
      - run: ./godelw publish bintray --url https://api.bintray.com --subject palantir --repository releases --user "$BINTRAY_USERNAME" --password "$BINTRAY_PASSWORD" --publish --downloads-list duo-bot
      - setup_remote_docker
      - *install-docker-client 
      - *build-docker-image
      - run: ./publish-docker.sh

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
      - changelog:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^master$/
