products:
  duo-bot:
    build:
      # CGO_ENABLED=0 makes our net-based go install statically- instead of dynamically-linked
      environment:
        CGO_ENABLED: "0"
      main-pkg: ./main
      os-archs:
        - os: linux
          arch: amd64
      version-var: github.com/palantir/duo-bot/cmd.version
    dist:
      dist-type:
        type: bin
group-id: com.palantir.duo-bot
